### ISSUE TITLE
csv file with empty cell does not work

### ISSUE THREAD

**Issue by ltemal94** [thesmartenergy/sparql-generate#12]
Hello, Maxime,

When I use a csv with cell which sometimes is empty cell or with cote " "  there is an Execption.
my csv is id,nom_voie,id_fantoir,numero,rep,code_insee,code_post,alias,nom_ld,x,y,commune,fant_voie,fant_ld,lat,lon
ADRNIVX_0000000270506477,Rue de ChichÃ©e,0140,6,"",89068,89800,"","",759949.1,6745941.7,Chablis,89068_0140S,,47.811133,3.800987

Please check  the message below :

Thank you 
Lynda

DEBUG [main] (IteratorPlanImpl.java:119) - Iterator execution failed:
org.apache.jena.sparql.expr.ExprEvalException: No evaluation for "id,nom_voie,id_fantoir,numero,rep,code_insee,code_post,alias,nom_ld,x,y,commune,fant_voie,fant_ld,lat,lon\r\nADRNIVX_0000000270506477,Rue de Chichée,0140,6,\"\",89068,89800,\"\",\"\",759949.1,6745941.7,Chablis,89068_0140S,,47.811133,3.800987"^^<http://www.iana.org/assignments/media-types/text/csv>
Caused by: java.lang.NullPointerException: columns to write should not be null on line 2
        at org.supercsv.io.AbstractCsvWriter.writeRow(AbstractCsvWriter.java:177)
        at org.supercsv.io.AbstractCsvWriter.writeRow(AbstractCsvWriter.java:143)
        at org.supercsv.io.CsvListWriter.write(CsvListWriter.java:71)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.library.ITER_CSV.exec(ITER_CSV.java:95)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorFunctionBase1.exec(IteratorFunctionBase1.java:57)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorFunctionBase.exec(IteratorFunctionBase.java:29)
        at com.github.thesmartenergy.sparql.generate.jena.iterator.IteratorStreamFunctionBase.exec(IteratorStreamFunctionBase.java:78)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.lambda$exec$2(IteratorPlanImpl.java:102)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.IteratorPlanImpl.exec(IteratorPlanImpl.java:99)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:325)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:331)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:308)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:292)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:277)
        at com.github.thesmartenergy.sparql.generate.jena.engine.impl.RootPlanImpl.exec(RootPlanImpl.java:259)
        at com.github.thesmartenergy.sparql.generate.jena.SPARQLGenerateCli.main(SPARQLGenerateCli.java:156)

**Comment by maximelefrancois86** [comment]
Hi Lynda, 

I think we did fix this bug already and the fix should be shipped with the next release. 
Please check with the most recent sources :-)

Best,
Maxime

**Comment by maximelefrancois86** [comment]
fixed a little bug in the code of fun:CSV. Please check again with the latest sources, and keep me updated
